/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appCanGeocode() {
        String geoclientKey = System.getenv(App.GEOCLIENT_KEY_ENV_VARIABLE);
        assertNotNull(geoclientKey);
        App classUnderTest = new App(geoclientKey);
        assertNotNull(classUnderTest.geocode("E 53 st and 3 ave"), "geocode should return a result");
    }
}
